{% set version = "0.2.0" %}

package:
  name: jupikchr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupikchr/jupikchr-{{ version }}.tar.gz
  sha256: cbe904cc82abc70ab18983ec6c1df86f2830721169ca0204cbb92321376504f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.7.1,<4
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ipywidgets >=7,<9
    - jupyterlab-markup

test:
  imports:
    - jupikchr
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupikchr.*OK" labextensions
  requires:
    - pip
    - m2-grep  # [win]

about:
  home: https://pypi.org/project/jupikchr
  summary: pikchr text-based diagrams for JupyterLab, etc.
  dev_url: https://github.com/deathbeds/jupikchr
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - src/jupikchr/_d/share/jupyter/labextensions/@deathbeds/jupikchr/static/third-party-licenses.json


extra:
  recipe-maintainers:
    - bollwyvl
